# data
driving_model: [
  "MOHC-HadGEM2-ES",
  "MPI-M-MPI-ESM", # MPI-M-MPI-ESM-LR_REMO2015 & MPI-M-MPI-ESM-MR_ICTP-RegCM4-7
  "NCC-NorESM1-M"
  ]
rcm_model: [
  "REMO2015",
  "ICTP-RegCM4-7",
  ]
experiment: ["historical", "rcp26", "rcp85"]
variable: ["hurs", "pr", "rsds", "rsus", "sfcWind", "tas"]
time_freq_hr: 3

# extract
# Set for Paracou
xutm: 5.267241344232334
yutm: -52.92436802555797
tz: "America/Cayenne"
extrapolation_time_freq: 0.5
plot_variables: ["rainfall", "snet", "temperature", "vpd", "ws"]

# singularity
troll: "https://github.com/sylvainschmitt/singularity-troll/releases/download/0.0.3/sylvainschmitt-singularity-troll.latest.sif"
