__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "24:00:00"
  partition: "agap_normal"

download:
  jobname: "download"
  mem: "4G"
  cpus: 1
  time: "24:00:00"  
  partition: "agap_normal"
  
extract_var:
  jobname: "extract_var"
  mem: "40G"
  cpus: 10
  time: "1:00:00"  
  partition: "agap_short"

join_exp:
  jobname: "join_exp"
  mem: "4G"
  cpus: 1
  time: "1:00:00"
  partition: "agap_short"

extrapolate:
  jobname: "extrapolate"
  mem: "4G"
  cpus: 1
  time: "1:00:00" 
  partition: "agap_short"
  
reformat:
  jobname: "reformat"
  mem: "4G"
  cpus: 1
  time: "1:00:00"  
  partition: "agap_short"

plot:
  jobname: "plot"
  mem: "4G"
  cpus: 1
  time: "1:00:00"  
  partition: "agap_short"
  