__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "24:00:00"

download:
  jobname: "download"
  mem: "4G"
  cpus: 1
  time: "24:00:00"  
  
extract:
  jobname: "extract"
  mem: "40G"
  cpus: 10
  time: "1:00:00"  

join_exp:
  jobname: "join_exp"
  mem: "4G"
  cpus: 1
  time: "1:00:00"  

join_exp:
  jobname: "join_exp"
  mem: "4G"
  cpus: 1
  time: "1:00:00"  

extrapolate:
  jobname: "extrapolate"
  mem: "4G"
  cpus: 1
  time: "1:00:00"  

plot:
  jobname: "plot"
  mem: "4G"
  cpus: 1
  time: "1:00:00"  
  