#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esg-dn1.nsc.liu.se - 2023/04/18 13:47:21
# Search URL: https://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=cordex.output.SAM-22.ICTP.MPI-M-MPI-ESM-MR.rcp85.r1i1p1.RegCM4-7.v0.3hr.pr.v20190502|esgf-ictp.hpc.cineca.it
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=cordex.output.SAM-22.ICTP.MPI-M-MPI-ESM-MR.rcp85.r1i1p1.RegCM4-7.v0.3hr.pr.v20190502|esgf-ictp.hpc.cineca.it'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_200601010130-200612312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_200601010130-200612312230.nc' 'SHA256' 'd5103b3f943208f6d3047361df6c7cd1bb19ed35e539b6f2409f4685e6d0091b'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_200701010130-200712312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_200701010130-200712312230.nc' 'SHA256' '0dfec02be4770e2b51fabf0e0c5058b01cd813632700891218356d4678a400e1'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_200801010130-200812312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_200801010130-200812312230.nc' 'SHA256' 'dc9f941d0791d6629bf1a2ebc8fdd7225daae911befc7cfbabb7f511a864d383'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_200901010130-200912312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_200901010130-200912312230.nc' 'SHA256' '4038708dfc656bf535e5ad82ff467690697877990180788ef682fbe99a5e902b'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201001010130-201012312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201001010130-201012312230.nc' 'SHA256' '2a530d07ff0cb4f020d77ae16428d8a89f4239dbae93c2ba975ec05dc049a3cc'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201101010130-201112312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201101010130-201112312230.nc' 'SHA256' '7dcf2232a5ae4ad21ff9db3bf77450d8e920dfb84976bc7a7dd4b8d92095b5cb'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201201010130-201212312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201201010130-201212312230.nc' 'SHA256' 'e1533057bbbba7f4b0725b0be0670e28fc607d0b5169601cb113ecab010d2918'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201301010130-201312312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201301010130-201312312230.nc' 'SHA256' '6f2391e48bf4f46e89c5d169dfa7f08a31417fdb5a4f4e85bd56eccf4111b066'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201401010130-201412312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201401010130-201412312230.nc' 'SHA256' '82ce9d1d225340ab6b374af68ce6ad5c17185673235ab988ddf3e6a3d3e475cc'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201501010130-201512312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201501010130-201512312230.nc' 'SHA256' '557883a484152de6ad3db6279ca473676a8b2a62715a294976b492c7e759ca60'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201601010130-201612312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201601010130-201612312230.nc' 'SHA256' 'ff44c07a1d43443d910371444dd5586d939fe9201f22f3791908a1aa6afacc61'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201701010130-201712312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201701010130-201712312230.nc' 'SHA256' 'a52815897bf3a99e9d64076b0317a968d0ed61f086ba6184d4cec7992699ac8d'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201801010130-201812312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201801010130-201812312230.nc' 'SHA256' '63f5c7d34ba340a93f5f6cfbeb16b80761534acbe4feb8f76c3cc8be0a6d3b2f'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201901010130-201912312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_201901010130-201912312230.nc' 'SHA256' 'ba1f6337fc78d1048bc3323c00cd7b943ce990af4337b067cfb10595d7f0ad11'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202001010130-202012312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202001010130-202012312230.nc' 'SHA256' '5866479c6b8e8c678b2f708418f6a299865df49bcc2f59b7bc66b11ca21f100a'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202101010130-202112312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202101010130-202112312230.nc' 'SHA256' '0fc088e9503e81e565ad7698949b31e82330bfa02d6619653c6d42b16b0784db'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202201010130-202212312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202201010130-202212312230.nc' 'SHA256' '3c7620de03f93ff63aa253fca84f974be2c1c5f1a7b50e42f34e4abf91a3cbe3'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202301010130-202312312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202301010130-202312312230.nc' 'SHA256' 'e844cf129e90fda772dcf1fee0077ab422b37eb8df0c1d4434603ef081f7f68f'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202401010130-202412312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202401010130-202412312230.nc' 'SHA256' '832387969278b7babd1f822b56735f711006da3ccfd59eb305577798d7dbd0e8'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202501010130-202512312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202501010130-202512312230.nc' 'SHA256' 'aac274581196e117a470f16bf1188129bd1377fc68053810532f3f4cee93cc4f'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202601010130-202612312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202601010130-202612312230.nc' 'SHA256' 'd92fe0b619ccd913a9c7b96dedbe13a85f994d9adb7736f5cbca8f4bf0fa9ccc'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202701010130-202712312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202701010130-202712312230.nc' 'SHA256' 'e9cff8309232524e517174cc821043dc7a884dead9ab2de5aa2c6dfb68fc60a8'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202801010130-202812312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202801010130-202812312230.nc' 'SHA256' '1683bca3cd830a84736e3c84165fb680edbd9a3e1712b02c2308e86c31db2459'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202901010130-202912312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_202901010130-202912312230.nc' 'SHA256' '29cdacb0590ac2bffab68a753f7a8c1831ef80433ec11769da183b3a63c8da80'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203001010130-203012312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203001010130-203012312230.nc' 'SHA256' '6c538d51329dba3c84f0ddf638457fb0af0f34d42784459b18d43cd14836a294'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203101010130-203112312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203101010130-203112312230.nc' 'SHA256' 'e6356525e68adb8d0d8a1ea73b5ba9905cb6eeb3961352e951f30fa3575ab52f'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203201010130-203212312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203201010130-203212312230.nc' 'SHA256' '2ecae0d9ca981dc25a357bb5ee299335d66758eca680e1c15c06ae16ab9b3d13'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203301010130-203312312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203301010130-203312312230.nc' 'SHA256' '4ec956c845f5884bf23cb8e945692bfbbf9cfb884b93752b9919133b1aa2e646'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203401010130-203412312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203401010130-203412312230.nc' 'SHA256' '7c03da8be71368a22d5cb620de72dc24f1ec8329ce21fa58c55ef44b5bbef56a'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203501010130-203512312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203501010130-203512312230.nc' 'SHA256' 'c96ce098a352f7c546a8fc456999a1f6a4c812580d67b40002d27115c6289381'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203601010130-203612312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203601010130-203612312230.nc' 'SHA256' '49b68f6782f3607a5e8aca7828f86178238c9ac3dead47e140a949f6d4f50a86'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203701010130-203712312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203701010130-203712312230.nc' 'SHA256' '67c245077699eafa219df4723a05a243b2b6e2256e9c5ede64b59da0df5fd0f4'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203801010130-203812312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203801010130-203812312230.nc' 'SHA256' '07a9277b113174d1df6403c30784962cdf67b2a431a0e7a590eb83b3025536fc'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203901010130-203912312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_203901010130-203912312230.nc' 'SHA256' '0a783487d4f3cdb165f222522188705f95549a91a934b6d897a0f91284af0b18'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204001010130-204012312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204001010130-204012312230.nc' 'SHA256' 'ee5d76a7ef850c8115e91589d6f120b82ee1a4fd34354d3304290e397612ba02'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204101010130-204112312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204101010130-204112312230.nc' 'SHA256' 'af337936a8c3d5f7231e14e6fc22b6c02193c2b4d53d16325ba6d6bc287559ec'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204201010130-204212312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204201010130-204212312230.nc' 'SHA256' 'ebb10c51c16227340f9a3a34d4be5deedb1d689396e6b037f5dec21a970f0fc5'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204301010130-204312312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204301010130-204312312230.nc' 'SHA256' '378501a18236a15e961691eaaeb1275aabc2d98874f388c4fd83ea873f57ef8e'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204401010130-204412312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204401010130-204412312230.nc' 'SHA256' '9c1ee4275a5aeb80e3389489212427ee5f67e79a5a1fa1408fe7eb3042cb0a73'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204501010130-204512312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204501010130-204512312230.nc' 'SHA256' '09714e30b97e78972d3bd32afd76ec8b45d7aa63b0dc45b08811ed950b848efc'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204601010130-204612312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204601010130-204612312230.nc' 'SHA256' '00f151c8e9f98c914457f6e3e099cc7444f38aed00ac12363b844d46e1e8c450'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204701010130-204712312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204701010130-204712312230.nc' 'SHA256' '65b8faf95e4ff96bcb7dac9811bf5847c537927b27edee561cc6c4cfea6f834a'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204801010130-204812312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204801010130-204812312230.nc' 'SHA256' '1f110753c9a271530df9e59ef032f5f476b1e15fe00fc2be4a1babe9b3d32c88'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204901010130-204912312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_204901010130-204912312230.nc' 'SHA256' '93c07317645b1804b204327d43b107b56f6dbeb9e3975332d6d9b8692cbdae54'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205001010130-205012312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205001010130-205012312230.nc' 'SHA256' '082185c7645d2139b35110e562bedbbee7f83e9550df0a11664822f0ef8cc670'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205101010130-205112312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205101010130-205112312230.nc' 'SHA256' '9ea3abebb2029f69de7ea04ca4c95f65f42ba72983948e0bcaaacc23ebbb3c3a'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205201010130-205212312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205201010130-205212312230.nc' 'SHA256' '804a654654eeb249ee067291d35abf801b500a464a59659d0ea2ada2025434df'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205301010130-205312312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205301010130-205312312230.nc' 'SHA256' 'bea343d142e21695d3207859810eb12d26705178314fa18eeab72cc2b64462eb'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205401010130-205412312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205401010130-205412312230.nc' 'SHA256' '9c8dee57e896ffab675cb8769b0cf0844a372bd941b2ef1efed3746ec4621710'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205501010130-205512312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205501010130-205512312230.nc' 'SHA256' '660bc031aa611b2b472454b75ac5c2ff4dc2f8afb16f57b43db921a7b63f5c36'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205601010130-205612312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205601010130-205612312230.nc' 'SHA256' '90ec9d999eb5e771fbe40fd1eaba50ff05e4adf25d28b9dbf5c6a5f18309083f'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205701010130-205712312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205701010130-205712312230.nc' 'SHA256' '992fdef664de1383a0e194bc5c51a8b2a6f5462d6a72da753bc6ab5718ea6782'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205801010130-205812312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205801010130-205812312230.nc' 'SHA256' '588c9c3534a0e200e4765877efcc30a91a0ade6ada9401b3a2babb42bf3e426f'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205901010130-205912312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_205901010130-205912312230.nc' 'SHA256' '341124d7d375dea7d08295e6f56d0a4d09a93a9f0a269272c2f1c61ee6d4414e'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206001010130-206012312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206001010130-206012312230.nc' 'SHA256' 'd6e6e5970b9b3f4103ce0b51c816755be88f922cf9e4b9e6aef6de4577d3ad85'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206101010130-206112312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206101010130-206112312230.nc' 'SHA256' '8f758d33909fe5e4bcebf37650f20c684171d7238abda422a2946569d82daa7f'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206201010130-206212312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206201010130-206212312230.nc' 'SHA256' 'e61cc1a639e4485f969dd2e3ff28492564a73dcdd52d82112490fb9b3559ff75'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206301010130-206312312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206301010130-206312312230.nc' 'SHA256' '80671f691ffca21e1ca3e8c041525054dac1528bf42ba913c9fa7837c4cb1de6'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206401010130-206412312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206401010130-206412312230.nc' 'SHA256' '9bbbe2b50d61e0ecb19dece3f7d35c881f1a67a33f78d8cf53c53daf6555d378'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206501010130-206512312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206501010130-206512312230.nc' 'SHA256' 'f302fcf1c0543c65d484e0a3461fdc8ab7d268eb8eaaa11e3f97d1ed2aba6121'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206601010130-206612312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206601010130-206612312230.nc' 'SHA256' '9bf7a27053c8994177ff7f060ff70858468f2c9c58e526be14307c761d0969a8'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206701010130-206712312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206701010130-206712312230.nc' 'SHA256' 'c5347b7be14b6867ff08c5c7377fbdd1e0a124c20411f407a738085b944642d3'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206801010130-206812312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206801010130-206812312230.nc' 'SHA256' 'b21ecebe30dd67eadb363f80c9fb94fa2a9b42941c7a3da2cec1c54c1f604391'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206901010130-206912312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_206901010130-206912312230.nc' 'SHA256' 'c55c629b161ad89a03c9d66c051904d5128821646b2c10fe80131ff8d6ba4b13'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207001010130-207012312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207001010130-207012312230.nc' 'SHA256' 'c922a6f9b6747ad91c9b9b064a3fecd2be32a88c04baf3a2b87c5474c4d8e80b'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207101010130-207112312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207101010130-207112312230.nc' 'SHA256' '5e348cd407be0c7264da680958036fed14162487ed7a763dd142d947fe2f3af3'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207201010130-207212312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207201010130-207212312230.nc' 'SHA256' '593195230114742d3f73a4133b89a67bfec13c17a203eb65217417e2acfc02f8'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207301010130-207312312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207301010130-207312312230.nc' 'SHA256' 'cf81940fde76ef4cfc1d4007ccba8e14e56bbf7e604dff558aba4412b4f3e192'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207401010130-207412312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207401010130-207412312230.nc' 'SHA256' '7816b74a2c07794248833c8fe236927a108bf83d1ae6fa1cb0a690cac0a7ecc7'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207501010130-207512312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207501010130-207512312230.nc' 'SHA256' 'ba39e54718c38da7482be649dd198e009580047cb3570bb63f1486c9aa846e2e'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207601010130-207612312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207601010130-207612312230.nc' 'SHA256' 'bc1b54321869a7776f1fdbcb967c7f6e21e3f7566dcf5c30425f138b2018ae77'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207701010130-207712312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207701010130-207712312230.nc' 'SHA256' 'd49620feb903259321c0e993914a46bac37911b95b7b46973a1320181c2d9620'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207801010130-207812312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207801010130-207812312230.nc' 'SHA256' 'dbebda88bd11513ad6fd3ec95cf42f18f00b01b53c6a9a12cf46ee4906b0d04c'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207901010130-207912312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_207901010130-207912312230.nc' 'SHA256' '84e80eff39e0367253f8a9584bb22035d8ba3eacb6b83687425c821e96afbc4a'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208001010130-208012312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208001010130-208012312230.nc' 'SHA256' '102b1ba6e224d521c93eab26fa972e4312c983c701264a5973adb76e53b5ba59'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208101010130-208112312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208101010130-208112312230.nc' 'SHA256' '2460123f50b6a0f504cc033a3f10c618c2b0526923773be274acf4ca1000e469'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208201010130-208212312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208201010130-208212312230.nc' 'SHA256' 'd992bbbe586046b9957cc95eafd93a09fcd9cc6b1f5b8e7bee6584afd395482e'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208301010130-208312312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208301010130-208312312230.nc' 'SHA256' '4c192fcf11c4ffe9dd5de34fbfc1a7d16ae9f35b3d2ce95423329c4966dd523f'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208401010130-208412312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208401010130-208412312230.nc' 'SHA256' 'f9eb89f30c00941a318e1af332303de64f7864755b0b385e8334001ca46742ca'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208501010130-208512312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208501010130-208512312230.nc' 'SHA256' '13141a6ef132009bddade99b4d95fb7ef43301c33b3fe3cb70ee9dce6a13c8d1'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208601010130-208612312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208601010130-208612312230.nc' 'SHA256' 'ea662dce00f3d5307a27451ee5c297c91276d60b2684806d322382473c142147'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208701010130-208712312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208701010130-208712312230.nc' 'SHA256' '5fabae40bba608905625ea50330bc73e596a006132125c2737f754573fef2577'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208801010130-208812312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208801010130-208812312230.nc' 'SHA256' '07796b202b93696c0240f782d2c66351bfcfdc6c785089c0400f4489cf7f0e65'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208901010130-208912312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_208901010130-208912312230.nc' 'SHA256' 'f318c4ef45a762d18e7975f8d23df6ed45a69dec062e3b7dc1f4e6ae8c75bd54'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209001010130-209012312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209001010130-209012312230.nc' 'SHA256' '38bf61b3873d264509dfd019783bf868e30241d59f92a5ece9af1cc4fa3df715'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209101010130-209112312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209101010130-209112312230.nc' 'SHA256' '0143faff130ea319fecf5be6d8485b433899b4e02b7e7ad8b6c7b4ae167bf5d1'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209201010130-209212312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209201010130-209212312230.nc' 'SHA256' 'a0df50ab1cc04ad7e2196d5045b45c03ac1d4112b7e57d4bcf62b27fc73944ae'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209301010130-209312312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209301010130-209312312230.nc' 'SHA256' '0ea44135db937bcdd1782efd44afcbfae32e94a8903bea9b3335be961cdbd01d'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209401010130-209412312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209401010130-209412312230.nc' 'SHA256' 'ea5c4d39b246f8d0cc163b17e2d6e01b432600733c7c02e72f863f97fe412816'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209501010130-209512312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209501010130-209512312230.nc' 'SHA256' '73ed09c5b1f6bbc0dbc351db4244e404ef5d73959a375648aaa43f6f66491267'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209601010130-209612312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209601010130-209612312230.nc' 'SHA256' 'a5ab10ee3304962f39411625b9d35906d097ed51d797fe95366f3e61b693f388'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209701010130-209712312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209701010130-209712312230.nc' 'SHA256' '41ee9ee004243519fcb2b51d3e718ca4618736cf4747ebaf0d4674489fc183fe'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209801010130-209812312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209801010130-209812312230.nc' 'SHA256' 'c97aa6e8fbdc9e2feffd9de535a7f360ac301b68ca26f32a7482175ba90899db'
'pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209901010130-209912312230.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/SAM-22/ICTP/MPI-M-MPI-ESM-MR/rcp85/r1i1p1/ICTP-RegCM4-7/v0/3hr/pr/v20190502/pr_SAM-22_MPI-M-MPI-ESM-MR_rcp85_r1i1p1_ICTP-RegCM4-7_v0_3hr_209901010130-209912312230.nc' 'SHA256' '090a3e2c9656956dc1e7c89c77b06da9f6155a930cdfc6f531ae1e3be0e8393d'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 94 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
